### ISSUE TITLE
 "The different entrances to the module lead to the same coordinates."

### ISSUE THREAD

**Issue by chunye-shanhui** [mim1q/MineCells#98] opened 2024-03-01 03:50 UTC
The current version being used is 1.7.1, and while playing, I noticed that both entrances of this module lead to the same coordinates, x:0 Z:-1024. Is this normal? What can I do to ensure that the destinations of the two entrances are different? (I tried going very far from one entrance, and the coordinates changed to x:0 Z:-2048).

If possible, please tell me if this was intentionally set up by you.

**Comment by mim1q** [comment] 2024-03-01 12:22
Hey, yes - this is intentional. It might change in the future but I'm keeping it like this for now, just for the simplicity of code.

What you can do is break the portal with the [x: 0 z:-2048] coordinates, take it back home and place it down - it'll keep its first coordinates

**Comment by chunye-shanhui** [comment] 2024-03-02 01:20
> Hey, yes - this is intentional. It might change in the future but I'm keeping it like this for now, just for the simplicity of code.
> 
> What you can do is break the portal with the [x: 0 z:-2048] coordinates, take it back home and place it down - it'll keep its first coordinates

I think I understand now.  So, what you're saying is that I need to move very far away from the spawn point coordinates to access the second dungeon entrance.  I tried running 1000 blocks away, but the dungeon coordinates didn't change, which is a bit disappointing.  Perhaps it would be better if you had to find the key to the second dungeon entrance in the first dungeon entrance?  That way, it might effectively prevent getting an unlimited amount of iron ingots and gold ingots in the dungeon.  Of course, this is just a random thought of mine.  Thank you very much for creating this mod, I appreciate it.  Thank you.

**Comment by mim1q** [comment] 2024-03-02 10:35
And thank you for playing the mod and for this conversation!
The current way these portal work is: they'll take you to the nearest-multiple-of-1024 coordinates. But keep in mind that if you travel the 1000 blocks to get a new portal, you have to place a *freshly crafted* one, cause the old one will probably have the coordinates bound to where you placed it first (it should say so in the item's tooltip!)

I'm thinking of ways to change the progression to make it more fun and intuitive, but it isn't a top priority thing right now :grin:

**Comment by abm991** [comment] 2024-03-31 01:31
Hello, author, [Sparse Structures] mod, not compatible with my cells, how to make him compatible with this mod?

**Comment by mim1q** [comment] 2024-03-31 05:54
@abm991 you should have opened another issue for this, it's unrelated to this one.
But anyway: Sparse Structure lets you configure each structures' spawn rates. You should set that field of the config file to
```json
{
  "structure": "minecells:black_bridge",
  "factor": 1
},
{
  "structure": "minecells:insufferable_crypt",
  "factor": 1
},
{
  "structure": "minecells:prison",
  "factor": 1
},
{
  "structure": "minecells:promenade",
  "factor": 1
},
{
  "structure": "minecells:promenade_wall_x",
  "factor": 1
},
{
  "structure": "minecells:promenade_wall_z",
  "factor": 1
},
{
  "structure": "minecells:ramparts",
  "factor": 1
},
{
  "structure": "minecells:ramparts_second",
  "factor": 1
}
```

Also - closing, since this seems to be a resolved issue? :thinking:

**Closed as completed by mim1q** 2024-03-31 05:54 UTC

**Comment by abm991** [comment] 2024-03-31 07:24
It doesn't work, and I don't know if it's a mistake with my modification path, or maybe I didn't say anything about it, I didn't say what the problem is, the problem is that the https://modrinth.com/mod/sparsestructures (Sparse Structures) MOD will cause you to enter the initial portal and get stuck in the wall, which won't happen without this mod installed, but you want the two to coexist, what should I do?
