### ISSUE TITLE
[Fabric 1.20.1] Mouse becomes uncomfortably smooth when camera shake is triggered

### ISSUE THREAD

**Issue by ButteredFluff** [mim1q/MineCells#114] opened 2024-05-17 07:01 UTC
The effect is similar to when you enter a minecart, and the mouse becomes weirdly smooth. Happens during any event where a camera shake is triggered, after the shake the mouse is stuck like this until death or relog. Mod version is 1.8.1 for Fabric 1.20.1, tested with every other possible mod disabled and issue still happened. Please help, thanks!

**Comment by mim1q** [comment] 2024-05-17 08:36
Thanks for reporting! Does it still happen if you set the Screen Shake to 0% in Accessibility Settings?

**Comment by ButteredFluff** [comment] 2024-05-17 10:44
It still does, yes, it's something with the trigger itself, and not the visual shake

**Comment by mim1q** [comment] 2024-05-17 11:29
Should be fixed with 930053c and https://github.com/mim1q/gimm1q/commit/727c44fbcb2393b676c50809f84b08848c788368. Found the best way to verify this is to quickly move your mouse in circles, and if it instead moves in a weird diagonal line, the issue is present 😅 

The bugfix patch is out on [Modrinth](https://modrinth.com/mod/minecells/version/1.8.2) and [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/minecells/files/5350552) now!

**Closed as completed by mim1q** 2024-05-17 11:29 UTC

**Comment by ButteredFluff** [comment] 2024-05-17 17:54
Thank you, can't wait to experience the mod!
