### ISSUE TITLE
[1.19.2] Tall Cages are not pushed by pistons as a whole and when mined, it dupes

### ISSUE THREAD

**Issue by kingkuys2123** [mim1q/MineCells#17] opened 2022-12-27 04:54 UTC
So I was in a middle of trapping a mob inside a Cage then this happened.. This also happened when being moved with Create contraptions, it only moves a part of the cage.

![2022-12-27_12 50 14](https://user-images.githubusercontent.com/114457180/209613091-4f0a8ea1-694f-476a-a3eb-b13d495308de.png)

When I mined them, each of the block drop it's own cage items

I tried fixing the dupe issue with this, it works but when I mined the top part of the cage it won't drop the item except when I mined the bottom one first.

`{
  "type": "minecraft:block",
  "pools": [
    {
      "bonus_rolls": 0.0,
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ],
      "entries": [
        {
          "type": "minecraft:item",
		  "conditions": [
            {
              "block": "minecells:cage",
              "condition": "minecraft:block_state_property",
              "properties": {
                "flipped": "false"
              }
            }
          ],
          "name": "minecells:cage"
        }
      ],
      "rolls": 1.0
    }
  ]
}`

**Comment by mim1q** [comment] 2022-12-27 08:18
Fixed the drop issue in b7719e7822d83f7f60a79e341146e70185e0c603! Your loot table was correct, it was just one boolean in my code that made it work improperly 😄 

Should I leave the cages pushable or make them break when pushed? There doesn't seem to be any way to make them both move at once without modifying pistons' code

**Comment by kingkuys2123** [comment] 2022-12-27 09:59
Hmm, I think its fine that you left the cages pushable because earlier I made a small cage (with a parrot inside) using only the top part of the tall cage soooo yeah a lot of building opportunities pops up in mind :) thank you for the fix! 😄

**Comment by mim1q** [comment] 2022-12-27 10:06
No problem! The issue is resolved, then. Closing :)

**Closed by mim1q** 2022-12-27 10:06 UTC
