### ISSUE TITLE
Elevator's in last update are worthless

### ISSUE THREAD

**Issue by FoxyTails1987** [mim1q/MineCells#53] opened 2023-07-26 21:46 UTC
Just updated and the elevator's don't work i mean they do but you fall right through them

**Comment by mim1q** [comment] 2023-07-26 22:12
Were you holding shift when getting on the elevator? If you crouch you will
fall through, that is intended behavior.

If it happens every time, even when not crouching for some reason I won't
be able to fix the issue for a week or so, I'm not going to be home.

śr., 26 lip 2023, 23:47 użytkownik Lima The Absol ***@***.***>
napisał:

**Comment by FoxyTails1987** [comment] 2023-07-26 22:14
nope i have done everything i can to stay on it to get out of my hole as i know how "mob's" work it's a type of horse entity but it's not even putting me on it i click it and it flys up without me while i'm just standing there stareing as my way of escape flys away as i keep pressing my button to call it back down as it works but its like i don't exist

**Comment by mim1q** [comment] 2023-07-27 02:33
Are you playing on a mod pack? What's the mod list?

**Comment by FoxyTails1987** [comment] 2023-07-27 03:43
how do i get a list of all the mods? i use multimc and have 425 mods it fixes after i downgrade 1 version down on 1.19.2 
![image](https://github.com/mim1q/MineCells/assets/36799615/086b7721-12f7-4bcf-ab40-fbbbc26799e8)

**Comment by mim1q** [comment] 2023-07-27 04:02
The last version that has changed *any* code regarding elevators is 1.5.0 🤔 And it's not even relevant code, it's just the bit for checking redstone power. I'll check if the problem exists for me when I come back, but this seems really weird.

**Comment by SngLol** [comment] 2024-03-03 14:59
I'm playing the Mod Pack AOF7 and I have the same issue, although it only regards player made elevators, the ones in Mine Cells dimensions work but not in the overworld.

https://github.com/mim1q/MineCells/assets/19615208/9d5dfa0b-b00f-4df8-8ffb-652505d32f85

It's the MineCells version 1.6.2
Is it fixed in 1.7.1?

EDIT:
I just updated to 1.7.1 and it is fixed! Thank you ^-^

**Comment by mim1q** [comment] 2024-03-03 20:05
> I'm playing the Mod Pack AOF7 and I have the same issue, although it only regards player made elevators, the ones in Mine Cells dimensions work but not in the overworld.
> 
>  javaw_NaWfAeqa8g.mp4 
> It's the MineCells version 1.6.2 Is it fixed in 1.7.1?
> 
> EDIT: I just updated to 1.7.1 and it is fixed! Thank you ^-^

Ayy that's awesome! Closing the issue, then :)
(the bugfix associated with this actually fixed *a lot* more than just these elevators lol)

**Closed as completed by mim1q** 2024-03-03 20:05 UTC
