### ISSUE TITLE
Crash with the mod Sinytra Connector

### ISSUE THREAD

**Issue by Bruskych** [mim1q/MineCells#118] opened 2024-05-20 13:01 UTC
All versions after 1.8.0 no longer work with the mod Sinytra Connector ( All versions before 1.7.4 worked fine

**Comment by mim1q** [comment] 2024-05-20 13:54
Duplicate of https://github.com/mim1q/MineCells/issues/111

Waiting for Connector devs to respond, it might be an issue on their side

**Closed as not planned by mim1q** 2024-05-20 13:54 UTC
