### ISSUE TITLE
3rd level teleports players on top of mountains where kills players

### ISSUE THREAD

**Issue by Miamlya** [mim1q/MineCells#106] opened 2024-04-09 19:07 UTC
Sometimes, the three-level dimension teleports players to the tops of mountains.

**Comment by mim1q** [comment] 2024-04-11 08:42
Likely a duplicate of [the previous issue](https://github.com/mim1q/MineCells/issues/105)

**Closed as not planned by mim1q** 2024-04-11 08:42 UTC

**Comment by Miamlya** [comment] 2024-04-11 21:37
![image](https://github.com/mim1q/MineCells/assets/145864992/61a8afed-9f31-4a5f-8c26-11cd685a6863)

**Comment by Miamlya** [comment] 2024-04-11 21:38
Maybe it would be helpful; this location damages survival players
